using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Text;
using UnityEditor;

public class NewBehaviourScript
{
    // Start is called before the first frame update
    [MenuItem("Test/TestLz4")]
    public static void TestLz4()
    {
        string tt = "sdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfwsdafdfafsafdsadfasfasf safsadfqwdfw";
        //byte[] arr = Encoding.ASCII.GetBytes(tt);
        byte[] arr = new byte[60208];
        for(int i = 0; i < arr.Length; ++i)
        {
            arr[i] = (byte)Random.Range(0, 256);
        }
        byte[] arr2;//= new byte[arr.Length * 10];
        int len = CommonUtils.Lz4Compress(arr, out arr2);

        System.Array.Resize(ref arr2, len);

        byte[] arr3 = new byte[arr.Length * 2];
        int len2 = CommonUtils.Lz4Decompress(arr2,arr3);

        for(int i = 0; i < len2;++i)
        {
            if(arr3[i] != arr[i])
            {
                Debug.Log("false");
                return;
            }
        }

        Debug.Log(len2 == arr.Length);
        //string tt2 = Encoding.ASCII.GetString(arr3,0,len2);
        //Debug.Log(tt2);
    }

    [MenuItem("Test/TestCrx")]
    public static void TestCrx()
    {
        CommonUtils.Ctx ctx = CommonUtils.Ctx.New(0123456);
        string tt = "testLzCrx";
        byte[] arr = Encoding.ASCII.GetBytes(tt);
        ctx.Encode(arr, arr.Length);

        List<byte> bList = new List<byte>();
        CommonUtils.Ctx ctx2 = CommonUtils.Ctx.New(0123456);

        for (int i = 0; i < arr.Length; ++i)
        {
            byte[] tarr = new byte[1];
            tarr[0] = arr[i];
            ctx2.Decode(tarr, tarr.Length);
            bList.Add(tarr[0]);
        }

        string tt2 = Encoding.ASCII.GetString(bList.ToArray(), 0, arr.Length);
        Debug.Log(tt2);
    }
}
